apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-service
  labels:
    app: user-management-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-management-service
  template:
    metadata:
      labels:
        app: user-management-service
    spec:
      containers:
        - name: user-management-service
          image: ghcr.io/SamirMarin/user-management-service:b7c46b93ae6694c21fdac3ba8162f5ff569d281d
          ports:
            - containerPort: 1324
